version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: task_management_db
    environment:
      - POSTGRES_DB=TaskManagementSystem_DB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
